### PR TITLE
Keep _multibuild in submitted requests

### PR DESCRIPTION
**Pull request by okurz**
Related progress issue: https://progress.opensuse.org/issues/128603

### CODE REVIEW

**Comment by kalikiana** [comment]
Is this related to https://progress.opensuse.org/issues/128603?

**Comment by perlpunk** [comment]
Yeah, I'll approve when the issue is in the commit message.

**Comment by okurz** [comment]
Updated the git commit message solely from smartphone with git amend from within GitHub codespaces. A bit finicky but works. I wonder if there is an easier way

**Review by Martchus — APPROVED** [review]
Let's see what the reviewers will say.

**Review by perlpunk — APPROVED** [review]

**Pull request merged**
