### PR TITLE
Cleaner usage of temp files as subprocess flags

### PR DESCRIPTION
**Pull request by ingydotnet**
~~Based on #194 and #195~~

Based on #196

### CODE REVIEW

**Comment by okurz** [comment]
@mergify rebase

**Comment by ingydotnet** [comment]
I rebased #196 ( da122583a ) into this branch.

iow, PR is now based on #196.

**Review by okurz — COMMENTED** [review]
+1

**Comment by ingydotnet** [comment]
Rebased #196 branch to here in aec3dba

**Comment by okurz** [comment]
@mergifyio rebase

**Review by okurz — APPROVED** [review]

**Pull request merged**
