### PR TITLE
Revert "Add force_result feature and automatic tests"

### PR DESCRIPTION
**Pull request by kalikiana**
Reverts os-autoinst/scripts#121

See: https://progress.opensuse.org/issues/104923

### CODE REVIEW

**Comment by Martchus** [comment]
@perlpunk Since it is your PR, maybe you want to come up with a smaller diff to disable the feature for now?

**Comment by perlpunk** [comment]
I can do that, yeah

**Comment by perlpunk** [comment]
#126 was merged

**Comment by Martchus** [comment]
Then let's close this one.

**Pull request closed without merging**
