### PR TITLE
Support passing job settings when cloning job via PR description

### PR DESCRIPTION
**Pull request by Martchus**
See https://progress.opensuse.org/issues/130943

### CODE REVIEW

**Review by kalikiana — APPROVED** [review]

**Comment by perlpunk** [comment]
Considering every github user can schedule jobs - are there any settings that shouldn't be overridable? e.g. `PUBLISH_HDD_1`

**Comment by okurz** [comment]
> Considering every github user can schedule jobs - are there any settings that shouldn't be overridable? e.g. `PUBLISH_HDD_1`

Wait, how can every github user schedule jobs? For not trusted, unknown contributors github asks project owners to approve CI runs. Wouldn't that apply here?

**Comment by Martchus** [comment]
I suppose it would apply here. Creating/maintaining a list of settings to exclude seems also not very helpful because one can also already change the test code (and that test code can then change settings anyway).

**Comment by perlpunk** [comment]
True, those rules probably apply also to actions run when a comment is written.
Still, good that we talked about it IMHO :)

**Review by okurz — APPROVED** [review]
Let's hope you are right then :-)

**Pull request merged**
